export enum LookupKeys {
    BloodTypes = "lookup.BloodTypes",
    DonationTypes = "lookup.DonationTypes",
    InHouseTypes = "lookup.InHouseTypes",
    BloodBagTypes = "lookup.BloodBagTypes",
    AgencyTypes = "lookup.AgencyTypes",
    DonorStatus = "lookup.DonorStatus",
    BloodBagSizeTypes = "lookup.BloodBagSizeTypes",
    SpecialBagTypes = "lookup.SpecialBagTypes",
    ApheresisBagTypes = "lookup.ApheresisBagTypes",
    BloodBagCollectionTypes = "lookup.BloodBagCollectionTypes",
    CivilStatus = "lookup.CivilStatus",
    PhysicalExamResult = "lookup.PhysicalExamResult",
    PriorityLevel = "lookup.PriorityLevel",
    PatientType = "lookup.PatientType",
    Membership = "lookup.Membership",
    CrossMatchTypes = "lookup.CrossMatchTypes",
    Nationalities = "lookup.Nationalities",
    RelationsToDonor = "lookup.RelationsToDonor",
    HospitalTypes = "lookup.HospitalTypes",
    BloodDonator = "lookup.BloodDonator",
}