//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBIS.Application {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PdfTemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PdfTemplates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BBIS.Application.PdfTemplates", typeof(PdfTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///&lt;style&gt;
        ///.text-center { text-align: center; }
        ///&lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///
        ///&lt;h1 class=&quot;text-center&quot;&gt;{InstitutionName}&lt;/h1&gt;
        ///&lt;h3 class=&quot;text-center&quot;&gt;Blood Compatibility Result Form&lt;/h1&gt;
        ///
        ///&lt;div&gt;
        ///	&lt;table&gt;
        ///		&lt;tr&gt;
        ///			&lt;td&gt;&lt;span&gt;Patient Name: {PatientName}&lt;/span&gt;&lt;/td&gt;
        ///			&lt;td&gt;&lt;span&gt;Patient No.: {PatientNo}&lt;/span&gt;&lt;/td&gt;
        ///			&lt;td&gt;&lt;span&gt;Ward/Room No.: {RoomNo}&lt;/span&gt;&lt;/td&gt;
        ///		&lt;/tr&gt;
        ///		&lt;tr&gt;
        ///			&lt;td&gt;&lt;span&gt;Birthdate: {Birthdate}&lt;/span&gt;&lt;/td&gt;
        ///			&lt;td&gt;&lt;span&gt;Age: {Age}&lt;/span&gt;&lt;/td&gt;
        ///			&lt;td&gt;&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CrossMatchResultPdf {
            get {
                return ResourceManager.GetString("CrossMatchResultPdf", resourceCulture);
            }
        }
    }
}
